[package]
name = "ankiconnect-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.11"
serde = { version = "1.0.217", features = ["derive"] }
ureq = "3.0.0-rc5"
serde_json = "1.0.135"

[dev-dependencies]
httpmock = "0.7.0-rc.1"